### PR TITLE
fix accepting malformed rlp packages

### LINKED ISSUE #48: RLP decoding does not limit list content to specified list length
When RLP decoding a list, the list length as specified in the RLP data is not enforced as a hard limit when decoding its content. 

For example, a 3-byte string in a list (eg `["ab"]`) is encoded as `c3 82 xx xx` ("list of 3 bytes" then "string of 2 bytes" then "string content"), but RLP such as `c1 82 xx xx` ("list of **2 bytes**" then "string of 2 bytes" then "string content") is accepted and decoded the same way.

I am opening this as an issue and not as a PR since I'm not 100% sure there is harm in accepting such malformed RLP, but reading the code it seems this lib is trying to reject non-canonical encodings in general.

FYI here is a set of tests that showcase a few problematic cases (marked as `// fails`):

```rust

#[test]
fn test_inner_length_capping_for_short_lists() {
	assert_eq!(Rlp::new(&vec![0xc0 + 0, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpInconsistentLengthAndData)); // fails
	assert_eq!(Rlp::new(&vec![0xc0 + 1, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpInconsistentLengthAndData)); // fails
	assert_eq!(Rlp::new(&vec![0xc0 + 2, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpInconsistentLengthAndData)); // fails
	assert_eq!(Rlp::new(&vec![0xc0 + 3, 0x82, b'a', b'b']).val_at::<String>(0), Ok("ab".to_owned())); // ok
	assert_eq!(Rlp::new(&vec![0xc0 + 4, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpIsTooShort)); // ok

}

#[test]
fn test_inner_length_capping_for_long_lists() {
	assert_eq!(Rlp::new(&vec![0xf7 + 1, 0, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpDataLenWithZeroPrefix)); // ok
	assert_eq!(Rlp::new(&vec![0xf7 + 1, 1, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpInconsistentLengthAndData)); // fails
	assert_eq!(Rlp::new(&vec![0xf7 + 1, 2, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpInconsistentLengthAndData)); // fails
	assert_eq!(Rlp::new(&vec![0xf7 + 1, 3, 0x82, b'a', b'b']).val_at::<String>(0), Ok("ab".to_owned())); // ok
	assert_eq!(Rlp::new(&vec![0xf7 + 1, 4, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpIsTooShort)); // ok
}
```

### PR DESCRIPTION
**Pull request by debris**
closes #48

### CODE REVIEW

File: rlp/tests/tests.rs [hunk 1]
```diff
@@ -437,4 +437,28 @@ fn test_rlp_is_int() {
...
\ No newline at end of file
+}
+
+/// test described in
+///
+/// https://github.com/paritytech/parity-common/issues/48
+#[test]
+fn test_inner_length_capping_for_short_lists() {
+	assert_eq!(Rlp::new(&vec![0xc0 + 0, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpIsTooShort));
+	assert_eq!(Rlp::new(&vec![0xc0 + 1, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpIsTooShort));
```
Comment (debris) [inline rlp/tests/tests.rs]: it reports `RlpIsTooShort` and not `RlpInconsistentLengthAndData`, because it's trying to take two bytes from a slice that contains only a single byte `&[b'a']`

File: rlp/tests/tests.rs [hunk 2]
```diff
@@ -437,4 +437,28 @@ fn test_rlp_is_int() {
 		let rlp = Rlp::new(&data);
 		assert_eq!(rlp.is_int(), false);
 	}
-}
\ No newline at end of file
+}
+
+/// test described in
+///
+/// https://github.com/paritytech/parity-common/issues/48
```
Comment (dvdplm) [inline rlp/tests/tests.rs]: No need for doc-comments here I think? Just `//` should be fine?
