### PR TITLE
fix accepting non-canonical rlp packages

### LINKED ISSUE #49: RLP decoding of non-canonical length encodings
According to the [RLP spec](https://github.com/ethereum/wiki/wiki/RLP#implementations), RLP elements (string or list) of encoded length > 55 should be encoded with a long encoding, and RLP elements with an encoded length <= 55 should be encoded with a short encoding.

It is currently possible to decode **RLP elements of length <= 55 encoded with the long encoding** without raising any error.

I am not sure there is harm in this, but this means we can have 2 different binary RLPs that have exactly the same semantics, which seems a bit fishy in some situations.

Some failing examples:

```rust
#[test]
fn test_canonical_string_encoding() {
	assert_ne!(Rlp::new(&vec![0xc0 + 4, 0xb7 + 1, 2, b'a', b'b']).val_at::<String>(0),
			   Rlp::new(&vec![0xc0 + 3, 0x82, b'a', b'b']).val_at::<String>(0)); // fails

}

#[test]
fn test_canonical_list_encoding() {
	assert_ne!(Rlp::new(&vec![0xc0 + 3, 0x82, b'a', b'b']).val_at::<String>(0),
			   Rlp::new(&vec![0xf7 + 1, 3, 0x82, b'a', b'b']).val_at::<String>(0)); // fails

}
```

### PR DESCRIPTION
**Pull request by debris**
closes #49

docs: https://github.com/ethereum/wiki/wiki/RLP#definition

### CODE REVIEW

File: rlp/tests/tests.rs [hunk 1]
```diff
@@ -450,15 +482,3 @@ fn test_inner_length_capping_for_short_lists() {
...
-/// test described in
-///
-/// https://github.com/paritytech/parity-common/issues/48
-#[test]
-fn test_inner_length_capping_for_long_lists() {
-	assert_eq!(Rlp::new(&vec![0xf7 + 1, 0, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpDataLenWithZeroPrefix));
-	assert_eq!(Rlp::new(&vec![0xf7 + 1, 1, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpIsTooShort));
-	assert_eq!(Rlp::new(&vec![0xf7 + 1, 2, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpIsTooShort));
-	assert_eq!(Rlp::new(&vec![0xf7 + 1, 3, 0x82, b'a', b'b']).val_at::<String>(0), Ok("ab".to_owned()));
-	assert_eq!(Rlp::new(&vec![0xf7 + 1, 4, 0x82, b'a', b'b']).val_at::<String>(0), Err(DecoderError::RlpIsTooShort));
```
Comment (debris) [inline rlp/tests/tests.rs]: actually all of these tests return error, cause `0xf7` requeires a list that is at least 55 bytes long. 

`test_canonical_list_encoding` replaces this test

**Comment by debris** [comment]
ping @dvdplm :)
